apiVersion: v1
kind: Service
metadata:
  name: bancodigital-api
  namespace: banco-digital
spec:
  type: LoadBalancer
  selector:
    app: bancodigital-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
